<div class="container">
	<div class="row justify-content-center">
		<div class="col-7">
			<h1>Miniframework está funcionando!</h1>
		</div>
	</div>

	<div class="row justify-content-center">
		<div class="col-12">
			<p>
				O framework foi desenvolvido com a intenção de compreender a arquitetura MVC!
			</p>
			<p>
  			
				Neste mini framework temos a utilização do composer para efetuar o gerenciamento de dependência, efetuando a conexão entre as estruturas.
			</p>
	</div>  	
	</div>
		<div class="align-bottom" align="center">
			<a class="btn btn-primary" href="https://www.devmedia.com.br/introducao-ao-padrao-mvc/29308" role="button">Conheca mais sobre MVC</a>
			<a class="btn btn-primary" href="https://king.host/blog/2018/02/composer-o-que-e-como-instalar-como-usar/" role="button">Conheca mais sobre Composer</a>
	</div>
</div>